#!/bin/bash

############################################
# LinuxFlow - Report Generator Module
############################################


##################################################
# Report Directory
##################################################

REPORT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/reports"


##################################################
# Function : initialize_report_directory
# Purpose  : Create report directory if required
##################################################

initialize_report_directory() {

    if [ ! -d "$REPORT_DIR" ]; then

        if ! mkdir -p "$REPORT_DIR"; then
            error "Unable to create report directory."
            return 1
        fi

    fi

    return 0
}


##################################################
# Function : generate_report_name
# Purpose  : Generate unique report filename
##################################################

generate_report_name() {

    local report_type="$1"
    local timestamp
    local filename
    local counter=1

    timestamp=$(date +"%Y%m%d_%H%M%S")

    filename="linuxflow_${report_type}_${timestamp}.txt"

    while [ -e "$REPORT_DIR/$filename" ]; do
        filename="linuxflow_${report_type}_${timestamp}_${counter}.txt"
        ((counter++))
    done

    echo "$filename"
}

##################################################
# Function : generate_system_report
# Purpose  : Generate system summary report
##################################################

generate_system_report() {

    header

    echo "========== Generate System Report =========="
    echo

    if ! initialize_report_directory; then
        pause
        return
    fi

    report_name=$(generate_report_name "system")
    report_file="$REPORT_DIR/$report_name"

    echo "Report Type : System Summary"
    echo "Report File : $report_file"
    echo

    read -p "Generate system report? (Y/N): " confirm

    case "$confirm" in

        Y|y)
            ;;

        N|n)
            warning "Report generation cancelled."
            pause
            return
            ;;

        *)
            error "Invalid choice."
            pause
            return
            ;;
    esac


    ##################################################
    # Generate Report
    ##################################################

    {

        echo "============================================================"
        echo "                 LinuxFlow System Report"
        echo "============================================================"
        echo

        echo "Generated On : $(date '+%d-%m-%Y %H:%M:%S')"
        echo "Generated By : $(whoami)"

        echo
        echo "============================================================"
        echo " SYSTEM INFORMATION"
        echo "============================================================"
        echo

        echo "Hostname       : $(hostname)"
        echo "Kernel         : $(uname -r)"
        echo "Architecture   : $(uname -m)"

        if [ -f /etc/os-release ]; then

            os_name=$(awk -F= '
                /^PRETTY_NAME=/ {
                    gsub(/"/,"",$2)
                    print $2
                }
            ' /etc/os-release)

            echo "Operating System : ${os_name:-Unknown}"

        else
            echo "Operating System : Unknown"
        fi


        ##################################################
        # Uptime
        ##################################################

        echo
        echo "============================================================"
        echo " UPTIME"
        echo "============================================================"
        echo

        echo "Uptime : $(uptime -p 2>/dev/null || uptime)"


        ##################################################
        # CPU Information
        ##################################################

        echo
        echo "============================================================"
        echo " CPU INFORMATION"
        echo "============================================================"
        echo

        echo "CPU Cores : $(nproc 2>/dev/null || echo "Unknown")"

        cpu_model=$(awk -F: '
            /model name/ {
                gsub(/^[ \t]+/, "", $2)
                print $2
                exit
            }
        ' /proc/cpuinfo 2>/dev/null)

        echo "CPU Model : ${cpu_model:-Unknown}"

        if [ -r /proc/loadavg ]; then

            read -r load1 load5 load15 _ < /proc/loadavg

            echo "Load Average (1 min)  : $load1"
            echo "Load Average (5 min)  : $load5"
            echo "Load Average (15 min) : $load15"

        fi


        ##################################################
        # Memory Information
        ##################################################

        echo
        echo "============================================================"
        echo " MEMORY INFORMATION"
        echo "============================================================"
        echo

        free -h


        ##################################################
        # Disk Information
        ##################################################

        echo
        echo "============================================================"
        echo " DISK USAGE"
        echo "============================================================"
        echo

        df -hP \
            -x tmpfs \
            -x devtmpfs \
            -x iso9660 \
            -x squashfs \
            -x overlay \
            2>/dev/null


        ##################################################
        # Block Devices
        ##################################################

        echo
        echo "============================================================"
        echo " BLOCK DEVICES"
        echo "============================================================"
        echo

        if command -v lsblk &>/dev/null; then

            lsblk -o NAME,SIZE,TYPE,FSTYPE,MOUNTPOINTS

        else

            echo "lsblk command is not available."

        fi


        ##################################################
        # Network Information
        ##################################################

        echo
        echo "============================================================"
        echo " NETWORK INFORMATION"
        echo "============================================================"
        echo

        if command -v ip &>/dev/null; then

            echo "IP Addresses:"
            echo "------------------------------------------------------------"

            ip -brief address 2>/dev/null

            echo
            echo "Default Route:"
            echo "------------------------------------------------------------"

            ip route show default 2>/dev/null

        else

            echo "'ip' command is not available."

        fi


        ##################################################
        # Logged In Users
        ##################################################

        echo
        echo "============================================================"
        echo " LOGGED IN USERS"
        echo "============================================================"
        echo

        if command -v who &>/dev/null; then

            who

        else

            echo "'who' command is not available."

        fi


        ##################################################
        # Report Footer
        ##################################################

        echo
        echo "============================================================"
        echo "               End of System Report"
        echo "============================================================"

    } > "$report_file" 2>&1


    ##################################################
    # Verify Report
    ##################################################

    if [ ! -f "$report_file" ]; then

        error "System report could not be created."
        pause
        return

    fi

    if [ ! -s "$report_file" ]; then

        error "Generated report is empty."
        rm -f "$report_file"
        pause
        return

    fi


    ##################################################
    # Success Information
    ##################################################

    report_size=$(du -h "$report_file" |
        awk '{print $1}')

    echo
    success "System report generated successfully."

    echo
    echo "Report Name : $report_name"
    echo "Report Path : $report_file"
    echo "Report Size : $report_size"

    pause
}



##################################################
# Function : generate_user_group_report
# Purpose  : Generate users and groups report
##################################################

generate_user_group_report() {

    header

    echo "========== Generate User & Group Report =========="
    echo

    if ! initialize_report_directory; then
        pause
        return
    fi

    report_name=$(generate_report_name "users_groups")
    report_file="$REPORT_DIR/$report_name"

    echo "Report Type : User & Group"
    echo "Report File : $report_file"
    echo

    read -p "Generate user & group report? (Y/N): " confirm

    case "$confirm" in

        Y|y)
            ;;

        N|n)
            warning "Report generation cancelled."
            pause
            return
            ;;

        *)
            error "Invalid choice."
            pause
            return
            ;;
    esac


    ##################################################
    # Generate Report
    ##################################################

    {

        echo "============================================================"
        echo "              LinuxFlow User & Group Report"
        echo "============================================================"
        echo

        echo "Generated On : $(date '+%d-%m-%Y %H:%M:%S')"
        echo "Generated By : $(whoami)"


        ##################################################
        # Normal Users
        ##################################################

        echo
        echo "============================================================"
        echo " NORMAL USERS"
        echo "============================================================"
        echo

        printf "%-20s %-10s %-10s %-25s %s\n" \
            "USERNAME" "UID" "GID" "HOME" "SHELL"

        printf "%-20s %-10s %-10s %-25s %s\n" \
            "--------------------" \
            "----------" \
            "----------" \
            "-------------------------" \
            "--------------------"

        awk -F: '
            $3 >= 1000 && $3 < 65534 {
                printf "%-20s %-10s %-10s %-25s %s\n",
                $1, $3, $4, $6, $7
            }
        ' /etc/passwd

        total_users=$(awk -F: '
            $3 >= 1000 && $3 < 65534 {
                count++
            }

            END {
                print count+0
            }
        ' /etc/passwd)

        echo
        echo "Total Normal Users : $total_users"


        ##################################################
        # Locked User Accounts
        ##################################################

        echo
        echo "============================================================"
        echo " LOCKED USER ACCOUNTS"
        echo "============================================================"
        echo

        locked_count=0

        while IFS=: read -r username _ uid _ _
        do

            if [ "$uid" -lt 1000 ] ||
               [ "$uid" -ge 65534 ]; then
                continue
            fi

            password_status=$(passwd -S "$username" 2>/dev/null |
                awk '{print $2}')

            if [ "$password_status" = "L" ] ||
               [ "$password_status" = "LK" ]; then

                echo "$username"
                ((locked_count++))
            fi

        done < /etc/passwd

        if [ "$locked_count" -eq 0 ]; then
            echo "No locked normal user accounts found."
        fi

        echo
        echo "Total Locked Users : $locked_count"


        ##################################################
        # Current Logged In Users
        ##################################################

        echo
        echo "============================================================"
        echo " CURRENT LOGGED IN USERS"
        echo "============================================================"
        echo

        if command -v who &>/dev/null; then

            login_data=$(who 2>/dev/null)

            if [ -n "$login_data" ]; then
                echo "$login_data"
            else
                echo "No active login sessions."
            fi

        else

            echo "'who' command is not available."

        fi


        ##################################################
        # Groups
        ##################################################

        echo
        echo "============================================================"
        echo " GROUPS"
        echo "============================================================"
        echo

        printf "%-25s %-10s %s\n" \
            "GROUP NAME" "GID" "MEMBERS"

        printf "%-25s %-10s %s\n" \
            "-------------------------" \
            "----------" \
            "------------------------------"

        awk -F: '{
            members=$4

            if (members == "")
                members="None"

            printf "%-25s %-10s %s\n",
            $1, $3, members
        }' /etc/group

        total_groups=$(awk -F: '
            END {
                print NR
            }
        ' /etc/group)

        echo
        echo "Total Groups : $total_groups"


        ##################################################
        # Administrative Users
        ##################################################

        echo
        echo "============================================================"
        echo " ADMINISTRATIVE USERS"
        echo "============================================================"
        echo

        admin_group=""

        if getent group wheel &>/dev/null; then

            admin_group="wheel"

        elif getent group sudo &>/dev/null; then

            admin_group="sudo"

        fi

        if [ -n "$admin_group" ]; then

            echo "Administrative Group : $admin_group"
            echo

            admin_members=$(getent group "$admin_group" |
                awk -F: '{print $4}')

            if [ -n "$admin_members" ]; then

                echo "Members:"
                echo "$admin_members" |
                    tr ',' '\n'

            else

                echo "No supplementary members found."

            fi

        else

            echo "No wheel/sudo administrative group detected."

        fi


        ##################################################
        # Users and Their Groups
        ##################################################

        echo
        echo "============================================================"
        echo " USER GROUP MEMBERSHIP"
        echo "============================================================"
        echo

        while IFS=: read -r username _ uid _ _
        do

            if [ "$uid" -ge 1000 ] &&
               [ "$uid" -lt 65534 ]; then

                echo "$username : $(id -nG "$username" 2>/dev/null)"

            fi

        done < /etc/passwd


        ##################################################
        # Report Footer
        ##################################################

        echo
        echo "============================================================"
        echo "             End of User & Group Report"
        echo "============================================================"

    } > "$report_file" 2>&1


    ##################################################
    # Verify Report
    ##################################################

    if [ ! -f "$report_file" ]; then

        error "User & group report could not be created."
        pause
        return

    fi

    if [ ! -s "$report_file" ]; then

        error "Generated report is empty."
        rm -f "$report_file"
        pause
        return

    fi


    ##################################################
    # Report Information
    ##################################################

    report_size=$(du -h "$report_file" |
        awk '{print $1}')

    echo
    success "User & group report generated successfully."

    echo
    echo "Report Name : $report_name"
    echo "Report Path : $report_file"
    echo "Report Size : $report_size"

    pause
}


##################################################
# Function : generate_storage_report
# Purpose  : Generate storage and filesystem report
##################################################

generate_storage_report() {

    header

    echo "========== Generate Storage Report =========="
    echo

    if ! initialize_report_directory; then
        pause
        return
    fi

    report_name=$(generate_report_name "storage")
    report_file="$REPORT_DIR/$report_name"

    echo "Report Type : Storage"
    echo "Report File : $report_file"
    echo

    read -p "Generate storage report? (Y/N): " confirm

    case "$confirm" in

        Y|y)
            ;;

        N|n)
            warning "Report generation cancelled."
            pause
            return
            ;;

        *)
            error "Invalid choice."
            pause
            return
            ;;
    esac


    ##################################################
    # Generate Report
    ##################################################

    {

        echo "============================================================"
        echo "                LinuxFlow Storage Report"
        echo "============================================================"
        echo

        echo "Generated On : $(date '+%d-%m-%Y %H:%M:%S')"
        echo "Generated By : $(whoami)"


        ##################################################
        # Block Devices
        ##################################################

        echo
        echo "============================================================"
        echo " BLOCK DEVICES"
        echo "============================================================"
        echo

        if command -v lsblk &>/dev/null; then

            lsblk -o \
                NAME,SIZE,TYPE,FSTYPE,FSAVAIL,FSUSE%,MOUNTPOINTS

        else

            echo "'lsblk' command is not available."

        fi


        ##################################################
        # Disk Usage
        ##################################################

        echo
        echo "============================================================"
        echo " FILESYSTEM DISK USAGE"
        echo "============================================================"
        echo

        df -hP \
            -x tmpfs \
            -x devtmpfs \
            -x iso9660 \
            -x squashfs \
            -x overlay \
            2>/dev/null


        ##################################################
        # Mounted Filesystems
        ##################################################

        echo
        echo "============================================================"
        echo " MOUNTED FILESYSTEMS"
        echo "============================================================"
        echo

        if command -v findmnt &>/dev/null; then

            findmnt \
                -o TARGET,SOURCE,FSTYPE,OPTIONS

        else

            mount

        fi


        ##################################################
        # Physical Volumes
        ##################################################

        echo
        echo "============================================================"
        echo " LVM - PHYSICAL VOLUMES"
        echo "============================================================"
        echo

        if command -v pvs &>/dev/null; then

            pvs \
                --noheadings \
                -o pv_name,vg_name,pv_size,pv_free 2>/dev/null

        else

            echo "LVM utilities are not available."

        fi


        ##################################################
        # Volume Groups
        ##################################################

        echo
        echo "============================================================"
        echo " LVM - VOLUME GROUPS"
        echo "============================================================"
        echo

        if command -v vgs &>/dev/null; then

            vgs \
                --noheadings \
                -o vg_name,pv_count,lv_count,vg_size,vg_free \
                2>/dev/null

        else

            echo "LVM utilities are not available."

        fi


        ##################################################
        # Logical Volumes
        ##################################################

        echo
        echo "============================================================"
        echo " LVM - LOGICAL VOLUMES"
        echo "============================================================"
        echo

        if command -v lvs &>/dev/null; then

            lvs \
                --noheadings \
                -o lv_name,vg_name,lv_size,lv_attr \
                2>/dev/null

        else

            echo "LVM utilities are not available."

        fi


        ##################################################
        # Swap Information
        ##################################################

        echo
        echo "============================================================"
        echo " SWAP INFORMATION"
        echo "============================================================"
        echo

        if command -v swapon &>/dev/null; then

            swap_data=$(swapon --show 2>/dev/null)

            if [ -n "$swap_data" ]; then

                echo "$swap_data"

            else

                echo "No active swap devices found."

            fi

        else

            echo "'swapon' command is not available."

        fi

        echo
        echo "Memory / Swap Summary:"
        echo "------------------------------------------------------------"

        free -h 2>/dev/null


        ##################################################
        # Filesystem Table
        ##################################################

        echo
        echo "============================================================"
        echo " /etc/fstab"
        echo "============================================================"
        echo

        if [ -r /etc/fstab ]; then

            grep -Ev \
                '^[[:space:]]*(#|$)' \
                /etc/fstab

        else

            echo "Unable to read /etc/fstab."

        fi


        ##################################################
        # Disk Identifiers
        ##################################################

        echo
        echo "============================================================"
        echo " DISK UUID AND FILESYSTEM INFORMATION"
        echo "============================================================"
        echo

        if command -v blkid &>/dev/null; then

            blkid 2>/dev/null

        else

            echo "'blkid' command is not available."

        fi


        ##################################################
        # Disk Usage Health
        ##################################################

        echo
        echo "============================================================"
        echo " DISK USAGE HEALTH"
        echo "============================================================"
        echo

        warning_count=0
        critical_count=0

        while read -r filesystem percent mountpoint
        do

            usage=${percent%\%}

            if [[ ! "$usage" =~ ^[0-9]+$ ]]; then
                continue
            fi

            if [ "$usage" -ge 90 ]; then

                echo "[CRITICAL] $mountpoint - ${usage}% used"
                ((critical_count++))

            elif [ "$usage" -ge 80 ]; then

                echo "[WARNING]  $mountpoint - ${usage}% used"
                ((warning_count++))

            else

                echo "[OK]       $mountpoint - ${usage}% used"

            fi

        done < <(
            df -P \
                -x tmpfs \
                -x devtmpfs \
                -x iso9660 \
                -x squashfs \
                -x overlay \
                2>/dev/null |
            awk 'NR > 1 {print $1, $5, $6}'
        )

        echo
        echo "Critical Filesystems : $critical_count"
        echo "Warning Filesystems  : $warning_count"


        ##################################################
        # Report Footer
        ##################################################

        echo
        echo "============================================================"
        echo "               End of Storage Report"
        echo "============================================================"

    } > "$report_file" 2>&1


    ##################################################
    # Verify Report
    ##################################################

    if [ ! -f "$report_file" ]; then

        error "Storage report could not be created."
        pause
        return

    fi

    if [ ! -s "$report_file" ]; then

        error "Generated report is empty."
        rm -f "$report_file"
        pause
        return

    fi


    ##################################################
    # Report Information
    ##################################################

    report_size=$(du -h "$report_file" |
        awk '{print $1}')

    echo
    success "Storage report generated successfully."

    echo
    echo "Report Name : $report_name"
    echo "Report Path : $report_file"
    echo "Report Size : $report_size"

    pause
}


##################################################
# Function : generate_service_report
# Purpose  : Generate system service report
##################################################

generate_service_report() {

    header

    echo "========== Generate Service Report =========="
    echo

    if ! initialize_report_directory; then
        pause
        return
    fi

    report_name=$(generate_report_name "services")
    report_file="$REPORT_DIR/$report_name"

    echo "Report Type : Services"
    echo "Report File : $report_file"
    echo

    read -p "Generate service report? (Y/N): " confirm

    case "$confirm" in

        Y|y)
            ;;

        N|n)
            warning "Report generation cancelled."
            pause
            return
            ;;

        *)
            error "Invalid choice."
            pause
            return
            ;;
    esac


    ##################################################
    # Generate Report
    ##################################################

    {

        echo "============================================================"
        echo "                LinuxFlow Service Report"
        echo "============================================================"
        echo

        echo "Generated On : $(date '+%d-%m-%Y %H:%M:%S')"
        echo "Generated By : $(whoami)"


        ##################################################
        # Systemd Check
        ##################################################

        echo
        echo "============================================================"
        echo " SYSTEMD INFORMATION"
        echo "============================================================"
        echo

        if ! command -v systemctl &>/dev/null; then

            echo "systemctl command is not available."
            echo
            echo "Unable to generate service information."

        else

            echo "System State : $(systemctl is-system-running 2>/dev/null || echo "unknown")"


            ##################################################
            # Running Services
            ##################################################

            echo
            echo "============================================================"
            echo " RUNNING SERVICES"
            echo "============================================================"
            echo

            systemctl list-units \
                --type=service \
                --state=running \
                --no-pager \
                --no-legend \
                2>/dev/null

            running_count=$(systemctl list-units \
                --type=service \
                --state=running \
                --no-legend \
                --no-pager \
                2>/dev/null |
                awk 'NF {count++} END {print count+0}')

            echo
            echo "Total Running Services : $running_count"


            ##################################################
            # Failed Services
            ##################################################

            echo
            echo "============================================================"
            echo " FAILED SERVICES"
            echo "============================================================"
            echo

            failed_services=$(systemctl \
                --failed \
                --type=service \
                --no-legend \
                --no-pager \
                2>/dev/null)

            if [ -n "$failed_services" ]; then

                echo "$failed_services"

            else

                echo "No failed services found."

            fi

            failed_count=$(systemctl \
                --failed \
                --type=service \
                --no-legend \
                --no-pager \
                2>/dev/null |
                awk 'NF {count++} END {print count+0}')

            echo
            echo "Total Failed Services : $failed_count"


            ##################################################
            # Enabled Services
            ##################################################

            echo
            echo "============================================================"
            echo " ENABLED SERVICES"
            echo "============================================================"
            echo

            systemctl list-unit-files \
                --type=service \
                --state=enabled \
                --no-pager \
                --no-legend \
                2>/dev/null

            enabled_count=$(systemctl list-unit-files \
                --type=service \
                --state=enabled \
                --no-pager \
                --no-legend \
                2>/dev/null |
                awk 'NF {count++} END {print count+0}')

            echo
            echo "Total Enabled Services : $enabled_count"


            ##################################################
            # Disabled Services
            ##################################################

            echo
            echo "============================================================"
            echo " DISABLED SERVICES"
            echo "============================================================"
            echo

            systemctl list-unit-files \
                --type=service \
                --state=disabled \
                --no-pager \
                --no-legend \
                2>/dev/null

            disabled_count=$(systemctl list-unit-files \
                --type=service \
                --state=disabled \
                --no-pager \
                --no-legend \
                2>/dev/null |
                awk 'NF {count++} END {print count+0}')

            echo
            echo "Total Disabled Services : $disabled_count"


            ##################################################
            # Failed Service Details
            ##################################################

            echo
            echo "============================================================"
            echo " FAILED SERVICE DETAILS"
            echo "============================================================"
            echo

            if [ "$failed_count" -gt 0 ]; then

                while read -r service
                do

                    [ -z "$service" ] && continue

                    echo
                    echo "------------------------------------------------------------"
                    echo "Service : $service"
                    echo "------------------------------------------------------------"
                    echo

                    systemctl status "$service" \
                        --no-pager \
                        -l \
                        2>/dev/null || true

                done < <(
                    systemctl \
                        --failed \
                        --type=service \
                        --no-legend \
                        --no-pager \
                        2>/dev/null |
                    awk '{print $1}'
                )

            else

                echo "No failed service details to display."

            fi


            ##################################################
            # Important Service Status
            ##################################################

            echo
            echo "============================================================"
            echo " IMPORTANT SERVICE STATUS"
            echo "============================================================"
            echo

            important_services=(
                "sshd"
                "firewalld"
                "crond"
            )

            printf "%-20s %-15s %-15s\n" \
                "SERVICE" "ACTIVE" "ENABLED"

            printf "%-20s %-15s %-15s\n" \
                "--------------------" \
                "---------------" \
                "---------------"

            for service in "${important_services[@]}"
            do

                if systemctl list-unit-files \
                    "${service}.service" \
                    --no-legend 2>/dev/null |
                    grep -q "^${service}.service"; then

                    active=$(systemctl is-active \
                        "$service" 2>/dev/null)

                    enabled=$(systemctl is-enabled \
                        "$service" 2>/dev/null)

                    printf "%-20s %-15s %-15s\n" \
                        "$service" \
                        "${active:-unknown}" \
                        "${enabled:-unknown}"

                else

                    printf "%-20s %-15s %-15s\n" \
                        "$service" \
                        "not-installed" \
                        "-"

                fi

            done


            ##################################################
            # Service Health Summary
            ##################################################

            echo
            echo "============================================================"
            echo " SERVICE HEALTH SUMMARY"
            echo "============================================================"
            echo

            echo "Running Services  : $running_count"
            echo "Enabled Services  : $enabled_count"
            echo "Disabled Services : $disabled_count"
            echo "Failed Services   : $failed_count"

            echo

            if [ "$failed_count" -gt 0 ]; then

                echo "[WARNING] One or more system services have failed."

            else

                echo "[OK] No failed system services detected."

            fi

        fi


        ##################################################
        # Report Footer
        ##################################################

        echo
        echo "============================================================"
        echo "               End of Service Report"
        echo "============================================================"

    } > "$report_file" 2>&1


    ##################################################
    # Verify Report
    ##################################################

    if [ ! -f "$report_file" ]; then

        error "Service report could not be created."
        pause
        return

    fi

    if [ ! -s "$report_file" ]; then

        error "Generated report is empty."
        rm -f "$report_file"
        pause
        return

    fi


    ##################################################
    # Report Information
    ##################################################

    report_size=$(du -h "$report_file" |
        awk '{print $1}')

    echo
    success "Service report generated successfully."

    echo
    echo "Report Name : $report_name"
    echo "Report Path : $report_file"
    echo "Report Size : $report_size"

    pause
}



##################################################
# Function : generate_security_report
# Purpose  : Generate system security report
##################################################

generate_security_report() {

    header

    echo "========== Generate Security Report =========="
    echo

    if ! initialize_report_directory; then
        pause
        return
    fi

    report_name=$(generate_report_name "security")
    report_file="$REPORT_DIR/$report_name"

    echo "Report Type : Security"
    echo "Report File : $report_file"
    echo

    read -p "Generate security report? (Y/N): " confirm

    case "$confirm" in

        Y|y)
            ;;

        N|n)
            warning "Report generation cancelled."
            pause
            return
            ;;

        *)
            error "Invalid choice."
            pause
            return
            ;;
    esac


    ##################################################
    # Generate Report
    ##################################################

    {

        echo "============================================================"
        echo "               LinuxFlow Security Report"
        echo "============================================================"
        echo

        echo "Generated On : $(date '+%d-%m-%Y %H:%M:%S')"
        echo "Generated By : $(whoami)"


        ##################################################
        # SELinux
        ##################################################

        echo
        echo "============================================================"
        echo " SELINUX STATUS"
        echo "============================================================"
        echo

        if command -v getenforce &>/dev/null; then

            echo "Current Mode : $(getenforce)"

            if command -v sestatus &>/dev/null; then
                echo
                sestatus
            fi

        else

            echo "SELinux utilities are not available."

        fi


        ##################################################
        # Firewall Status
        ##################################################

        echo
        echo "============================================================"
        echo " FIREWALL STATUS"
        echo "============================================================"
        echo

        if command -v firewall-cmd &>/dev/null; then

            if systemctl is-active --quiet firewalld 2>/dev/null; then

                echo "Firewalld Status : Active"

                firewall_zone=$(firewall-cmd \
                    --get-default-zone 2>/dev/null)

                echo "Default Zone     : ${firewall_zone:-Unknown}"

                echo
                echo "Active Zones:"
                echo "------------------------------------------------------------"

                firewall-cmd --get-active-zones 2>/dev/null

                echo
                echo "Firewall Configuration:"
                echo "------------------------------------------------------------"

                firewall-cmd --list-all 2>/dev/null

            else

                echo "Firewalld Status : Inactive"

            fi

        else

            echo "firewall-cmd is not available."

        fi


        ##################################################
        # SSH Security
        ##################################################

        echo
        echo "============================================================"
        echo " SSH SECURITY"
        echo "============================================================"
        echo

        if command -v sshd &>/dev/null; then

            ssh_service=""

            if systemctl list-unit-files sshd.service \
                --no-legend 2>/dev/null |
                grep -q '^sshd.service'; then

                ssh_service="sshd"

            elif systemctl list-unit-files ssh.service \
                --no-legend 2>/dev/null |
                grep -q '^ssh.service'; then

                ssh_service="ssh"

            fi

            if [ -n "$ssh_service" ]; then

                echo "SSH Service : $ssh_service"
                echo "Active      : $(systemctl is-active "$ssh_service" 2>/dev/null)"
                echo "Enabled     : $(systemctl is-enabled "$ssh_service" 2>/dev/null)"

            else

                echo "SSH systemd service could not be detected."

            fi

            echo

            if sshd -t 2>/dev/null; then

                ssh_config=$(sshd -T 2>/dev/null)

                echo "Effective SSH Configuration:"
                echo "------------------------------------------------------------"

                echo "Port                  : $(echo "$ssh_config" |
                    awk '$1=="port" {print $2; exit}')"

                echo "Permit Root Login     : $(echo "$ssh_config" |
                    awk '$1=="permitrootlogin" {print $2; exit}')"

                echo "Password Authentication : $(echo "$ssh_config" |
                    awk '$1=="passwordauthentication" {print $2; exit}')"

                echo "Public Key Authentication: $(echo "$ssh_config" |
                    awk '$1=="pubkeyauthentication" {print $2; exit}')"

                echo "Permit Empty Passwords: $(echo "$ssh_config" |
                    awk '$1=="permitemptypasswords" {print $2; exit}')"

                echo "Max Authentication Tries: $(echo "$ssh_config" |
                    awk '$1=="maxauthtries" {print $2; exit}')"

            else

                echo "SSH configuration contains errors or could not be validated."

            fi

        else

            echo "OpenSSH Server is not installed."

        fi


        ##################################################
        # Listening Network Ports
        ##################################################

        echo
        echo "============================================================"
        echo " LISTENING NETWORK PORTS"
        echo "============================================================"
        echo

        if command -v ss &>/dev/null; then

            ss -lntup 2>/dev/null

        else

            echo "'ss' command is not available."

        fi


        ##################################################
        # Logged In Users
        ##################################################

        echo
        echo "============================================================"
        echo " CURRENT LOGIN SESSIONS"
        echo "============================================================"
        echo

        if command -v who &>/dev/null; then

            login_data=$(who 2>/dev/null)

            if [ -n "$login_data" ]; then
                echo "$login_data"
            else
                echo "No active login sessions."
            fi

        else

            echo "'who' command is not available."

        fi


        ##################################################
        # Recent Successful Logins
        ##################################################

        echo
        echo "============================================================"
        echo " RECENT LOGIN HISTORY"
        echo "============================================================"
        echo

        if command -v last &>/dev/null; then

            last -n 10 2>/dev/null

        else

            echo "'last' command is not available."

        fi


      ##################################################
# Failed Login Attempts
##################################################

echo
echo "============================================================"
echo " RECENT FAILED LOGIN ATTEMPTS"
echo "============================================================"
echo

failed_logins=""

if command -v lastb &>/dev/null; then

    failed_logins=$(lastb -n 10 2>/dev/null |
        grep -v '^btmp begins' |
        grep -v '^[[:space:]]*$')

    if [ -n "$failed_logins" ]; then
        echo "$failed_logins"
    else
        echo "No recent failed login attempts found."
    fi

else

    echo "'lastb' command is not available."

fi



        ##################################################
        # Locked Normal User Accounts
        ##################################################

        echo
        echo "============================================================"
        echo " LOCKED NORMAL USER ACCOUNTS"
        echo "============================================================"
        echo

        locked_count=0

        while IFS=: read -r username _ uid _ _
        do

            if [ "$uid" -lt 1000 ] ||
               [ "$uid" -ge 65534 ]; then
                continue
            fi

            account_state=$(passwd -S "$username" 2>/dev/null |
                awk '{print $2}')

            if [ "$account_state" = "L" ] ||
               [ "$account_state" = "LK" ]; then

                echo "$username"
                ((locked_count++))
            fi

        done < /etc/passwd

        if [ "$locked_count" -eq 0 ]; then
            echo "No locked normal user accounts found."
        fi

        echo
        echo "Total Locked Users : $locked_count"


        ##################################################
        # Administrative Group
        ##################################################

        echo
        echo "============================================================"
        echo " ADMINISTRATIVE USERS"
        echo "============================================================"
        echo

        if getent group wheel &>/dev/null; then

            echo "Administrative Group : wheel"

            wheel_members=$(getent group wheel |
                awk -F: '{print $4}')

            if [ -n "$wheel_members" ]; then

                echo "Supplementary Members:"
                echo "$wheel_members" | tr ',' '\n'

            else

                echo "No supplementary wheel members."

            fi

        elif getent group sudo &>/dev/null; then

            echo "Administrative Group : sudo"

            sudo_members=$(getent group sudo |
                awk -F: '{print $4}')

            if [ -n "$sudo_members" ]; then

                echo "Supplementary Members:"
                echo "$sudo_members" | tr ',' '\n'

            else

                echo "No supplementary sudo members."

            fi

        else

            echo "No wheel/sudo administrative group detected."

        fi


        ##################################################
        # SUID Files
        ##################################################

        echo
        echo "============================================================"
        echo " SUID EXECUTABLE FILES"
        echo "============================================================"
        echo

        echo "Files with the SUID permission bit:"
        echo "------------------------------------------------------------"

        find / \
            -xdev \
            -type f \
            -perm -4000 \
            -print \
            2>/dev/null |
            sort


        ##################################################
        # World Writable Directories
        ##################################################

        echo
        echo "============================================================"
        echo " WORLD-WRITABLE DIRECTORIES"
        echo "============================================================"
        echo

        echo "World-writable directories on the root filesystem:"
        echo "------------------------------------------------------------"

        find / \
            -xdev \
            -type d \
            -perm -0002 \
            -print \
            2>/dev/null |
            sort


        ##################################################
        # Security Summary
        ##################################################

        echo
        echo "============================================================"
        echo " SECURITY SUMMARY"
        echo "============================================================"
        echo

        if command -v getenforce &>/dev/null; then
            echo "SELinux       : $(getenforce)"
        else
            echo "SELinux       : Unknown"
        fi

        if command -v firewall-cmd &>/dev/null; then

            if systemctl is-active --quiet firewalld 2>/dev/null; then
                echo "Firewall      : Active"
            else
                echo "Firewall      : Inactive"
            fi

        else

            echo "Firewall      : Not Available"

        fi

        if command -v sshd &>/dev/null; then
            echo "SSH Server    : Installed"
        else
            echo "SSH Server    : Not Installed"
        fi

        echo "Locked Users  : $locked_count"

        if [ -n "$failed_logins" ]; then
            echo "Failed Logins : Detected"
        else
            echo "Failed Logins : None Detected"
        fi


        ##################################################
        # Report Footer
        ##################################################

        echo
        echo "============================================================"
        echo "              End of Security Report"
        echo "============================================================"

    } > "$report_file" 2>&1


    ##################################################
    # Verify Report
    ##################################################

    if [ ! -f "$report_file" ]; then

        error "Security report could not be created."
        pause
        return

    fi

    if [ ! -s "$report_file" ]; then

        error "Generated report is empty."
        rm -f "$report_file"
        pause
        return

    fi


    ##################################################
    # Report Information
    ##################################################

    report_size=$(du -h "$report_file" |
        awk '{print $1}')

    echo
    success "Security report generated successfully."

    echo
    echo "Report Name : $report_name"
    echo "Report Path : $report_file"
    echo "Report Size : $report_size"

    pause
}



##################################################
# Function : generate_full_report
# Purpose  : Generate complete LinuxFlow system report
##################################################

generate_full_report() {

    header

    echo "========== Generate Full System Report =========="
    echo

    if ! initialize_report_directory; then
        pause
        return
    fi

    report_name=$(generate_report_name "full")
    report_file="$REPORT_DIR/$report_name"

    echo "Report Type : Full System Report"
    echo "Report File : $report_file"
    echo

    warning "This report may take a few seconds to generate."
    echo

    read -p "Generate full system report? (Y/N): " confirm

    case "$confirm" in

        Y|y)
            ;;

        N|n)
            warning "Report generation cancelled."
            pause
            return
            ;;

        *)
            error "Invalid choice."
            pause
            return
            ;;
    esac

    echo
    echo "Collecting system information..."


    ##################################################
    # Generate Full Report
    ##################################################

    {

        echo "============================================================"
        echo "               LinuxFlow Full System Report"
        echo "============================================================"
        echo

        echo "Generated On : $(date '+%d-%m-%Y %H:%M:%S')"
        echo "Generated By : $(whoami)"
        echo "Hostname     : $(hostname)"

        echo


        ##################################################
        # 1. System Information
        ##################################################

        echo "============================================================"
        echo " 1. SYSTEM INFORMATION"
        echo "============================================================"
        echo

        echo "Hostname     : $(hostname)"
        echo "Kernel       : $(uname -r)"
        echo "Architecture : $(uname -m)"

        if [ -r /etc/os-release ]; then

            os_name=$(awk -F= '
                /^PRETTY_NAME=/ {
                    gsub(/"/, "", $2)
                    print $2
                    exit
                }
            ' /etc/os-release)

            echo "Operating System : ${os_name:-Unknown}"

        else

            echo "Operating System : Unknown"

        fi

        echo "Uptime           : $(uptime -p 2>/dev/null || echo "Unknown")"
        echo "Boot Time        : $(uptime -s 2>/dev/null || echo "Unknown")"


        ##################################################
        # 2. CPU Information
        ##################################################

        echo
        echo "============================================================"
        echo " 2. CPU INFORMATION"
        echo "============================================================"
        echo

        echo "CPU Cores : $(nproc 2>/dev/null || echo "Unknown")"

        cpu_model=$(awk -F: '
            /model name/ {
                gsub(/^[ \t]+/, "", $2)
                print $2
                exit
            }
        ' /proc/cpuinfo 2>/dev/null)

        echo "CPU Model : ${cpu_model:-Unknown}"

        if [ -r /proc/loadavg ]; then

            read -r load1 load5 load15 _ < /proc/loadavg

            echo
            echo "Load Average:"
            echo "1 Minute   : $load1"
            echo "5 Minutes  : $load5"
            echo "15 Minutes : $load15"

        fi


        ##################################################
        # 3. Memory and Swap
        ##################################################

        echo
        echo "============================================================"
        echo " 3. MEMORY AND SWAP"
        echo "============================================================"
        echo

        free -h 2>/dev/null

        echo
        echo "Active Swap:"
        echo "------------------------------------------------------------"

        if command -v swapon &>/dev/null; then

            swap_data=$(swapon --show 2>/dev/null)

            if [ -n "$swap_data" ]; then
                echo "$swap_data"
            else
                echo "No active swap configured."
            fi

        else

            echo "'swapon' command is not available."

        fi


        ##################################################
        # 4. Storage
        ##################################################

        echo
        echo "============================================================"
        echo " 4. STORAGE INFORMATION"
        echo "============================================================"
        echo

        echo "Block Devices:"
        echo "------------------------------------------------------------"

        if command -v lsblk &>/dev/null; then

            lsblk -o \
                NAME,SIZE,TYPE,FSTYPE,FSAVAIL,FSUSE%,MOUNTPOINTS

        else

            echo "'lsblk' command is not available."

        fi

        echo
        echo "Filesystem Usage:"
        echo "------------------------------------------------------------"

        df -hP \
            -x tmpfs \
            -x devtmpfs \
            -x iso9660 \
            -x squashfs \
            -x overlay \
            2>/dev/null


        ##################################################
        # 5. LVM
        ##################################################

        echo
        echo "============================================================"
        echo " 5. LVM INFORMATION"
        echo "============================================================"
        echo

        echo "Physical Volumes:"
        echo "------------------------------------------------------------"

        if command -v pvs &>/dev/null; then
            pvs 2>/dev/null
        else
            echo "LVM utilities are not available."
        fi

        echo
        echo "Volume Groups:"
        echo "------------------------------------------------------------"

        if command -v vgs &>/dev/null; then
            vgs 2>/dev/null
        else
            echo "LVM utilities are not available."
        fi

        echo
        echo "Logical Volumes:"
        echo "------------------------------------------------------------"

        if command -v lvs &>/dev/null; then
            lvs 2>/dev/null
        else
            echo "LVM utilities are not available."
        fi


        ##################################################
        # 6. Users
        ##################################################

        echo
        echo "============================================================"
        echo " 6. USER INFORMATION"
        echo "============================================================"
        echo

        printf "%-20s %-10s %-25s %s\n" \
            "USERNAME" "UID" "HOME" "SHELL"

        printf "%-20s %-10s %-25s %s\n" \
            "--------------------" \
            "----------" \
            "-------------------------" \
            "--------------------"

        awk -F: '
            $3 >= 1000 && $3 < 65534 {
                printf "%-20s %-10s %-25s %s\n",
                $1, $3, $6, $7
            }
        ' /etc/passwd

        total_users=$(awk -F: '
            $3 >= 1000 && $3 < 65534 {
                count++
            }

            END {
                print count+0
            }
        ' /etc/passwd)

        echo
        echo "Total Normal Users : $total_users"


        ##################################################
        # 7. Groups
        ##################################################

        echo
        echo "============================================================"
        echo " 7. GROUP INFORMATION"
        echo "============================================================"
        echo

        printf "%-25s %-10s %s\n" \
            "GROUP NAME" "GID" "MEMBERS"

        awk -F: '{
            members=$4

            if (members == "")
                members="None"

            printf "%-25s %-10s %s\n",
            $1, $3, members
        }' /etc/group

        total_groups=$(awk 'END {print NR}' /etc/group)

        echo
        echo "Total Groups : $total_groups"


        ##################################################
        # 8. Logged In Users
        ##################################################

        echo
        echo "============================================================"
        echo " 8. ACTIVE LOGIN SESSIONS"
        echo "============================================================"
        echo

        if command -v who &>/dev/null; then

            login_data=$(who 2>/dev/null)

            if [ -n "$login_data" ]; then
                echo "$login_data"
            else
                echo "No active login sessions."
            fi

        else

            echo "'who' command is not available."

        fi


        ##################################################
        # 9. Network
        ##################################################

        echo
        echo "============================================================"
        echo " 9. NETWORK INFORMATION"
        echo "============================================================"
        echo

        if command -v ip &>/dev/null; then

            echo "Interfaces:"
            echo "------------------------------------------------------------"

            ip -brief address 2>/dev/null

            echo
            echo "Default Route:"
            echo "------------------------------------------------------------"

            ip route show default 2>/dev/null

        else

            echo "'ip' command is not available."

        fi

        echo
        echo "Listening Ports:"
        echo "------------------------------------------------------------"

        if command -v ss &>/dev/null; then
            ss -lntup 2>/dev/null
        else
            echo "'ss' command is not available."
        fi


        ##################################################
        # 10. Services
        ##################################################

        echo
        echo "============================================================"
        echo " 10. SERVICE INFORMATION"
        echo "============================================================"
        echo

        if command -v systemctl &>/dev/null; then

            running_services=$(systemctl list-units \
                --type=service \
                --state=running \
                --no-legend \
                --no-pager \
                2>/dev/null |
                awk 'NF {count++} END {print count+0}')

            failed_services=$(systemctl \
                --failed \
                --type=service \
                --no-legend \
                --no-pager \
                2>/dev/null |
                awk 'NF {count++} END {print count+0}')

            echo "Running Services : $running_services"
            echo "Failed Services  : $failed_services"

            echo
            echo "Failed Service List:"
            echo "------------------------------------------------------------"

            if [ "$failed_services" -gt 0 ]; then

                systemctl \
                    --failed \
                    --type=service \
                    --no-pager \
                    2>/dev/null

            else

                echo "No failed services detected."

            fi

        else

            echo "'systemctl' command is not available."

        fi


        ##################################################
        # 11. Firewall
        ##################################################

        echo
        echo "============================================================"
        echo " 11. FIREWALL"
        echo "============================================================"
        echo

        if command -v firewall-cmd &>/dev/null; then

            if systemctl is-active --quiet firewalld 2>/dev/null; then

                echo "Firewalld Status : Active"
                echo

                firewall-cmd --get-active-zones 2>/dev/null

                echo
                firewall-cmd --list-all 2>/dev/null

            else

                echo "Firewalld Status : Inactive"

            fi

        else

            echo "Firewalld is not available."

        fi


        ##################################################
        # 12. SELinux
        ##################################################

        echo
        echo "============================================================"
        echo " 12. SELINUX"
        echo "============================================================"
        echo

        if command -v getenforce &>/dev/null; then

            echo "SELinux Mode : $(getenforce)"

            if command -v sestatus &>/dev/null; then
                echo
                sestatus
            fi

        else

            echo "SELinux information is unavailable."

        fi


        ##################################################
        # 13. SSH
        ##################################################

        echo
        echo "============================================================"
        echo " 13. SSH INFORMATION"
        echo "============================================================"
        echo

        if command -v sshd &>/dev/null; then

            if sshd -t 2>/dev/null; then

                ssh_config=$(sshd -T 2>/dev/null)

                echo "Port              : $(echo "$ssh_config" |
                    awk '$1=="port" {print $2; exit}')"

                echo "Root Login        : $(echo "$ssh_config" |
                    awk '$1=="permitrootlogin" {print $2; exit}')"

                echo "Password Auth     : $(echo "$ssh_config" |
                    awk '$1=="passwordauthentication" {print $2; exit}')"

                echo "Public Key Auth   : $(echo "$ssh_config" |
                    awk '$1=="pubkeyauthentication" {print $2; exit}')"

            else

                echo "SSH configuration validation failed."

            fi

        else

            echo "OpenSSH Server is not installed."

        fi


        ##################################################
        # 14. Failed Logins
        ##################################################

        echo
        echo "============================================================"
        echo " 14. RECENT FAILED LOGIN ATTEMPTS"
        echo "============================================================"
        echo

        failed_login_data=""

        if command -v lastb &>/dev/null; then

            failed_login_data=$(lastb -n 10 2>/dev/null |
                grep -v '^btmp begins' |
                grep -v '^[[:space:]]*$')

            if [ -n "$failed_login_data" ]; then
                echo "$failed_login_data"
            else
                echo "No recent failed login attempts found."
            fi

        else

            echo "'lastb' command is not available."

        fi


        ##################################################
        # 15. Cron
        ##################################################

        echo
        echo "============================================================"
        echo " 15. CRON INFORMATION"
        echo "============================================================"
        echo

        if command -v systemctl &>/dev/null; then

            if systemctl list-unit-files crond.service \
                --no-legend 2>/dev/null |
                grep -q '^crond.service'; then

                echo "Cron Service Active  : $(systemctl is-active crond 2>/dev/null)"
                echo "Cron Service Enabled : $(systemctl is-enabled crond 2>/dev/null)"

            fi

        fi

        echo
        echo "Current User Crontab:"
        echo "------------------------------------------------------------"

        if command -v crontab &>/dev/null; then

            crontab_data=$(crontab -l 2>/dev/null)

            if [ -n "$crontab_data" ]; then
                echo "$crontab_data"
            else
                echo "No crontab entries for current user."
            fi

        else

            echo "'crontab' command is not available."

        fi


        ##################################################
        # 16. /etc/fstab
        ##################################################

        echo
        echo "============================================================"
        echo " 16. FILESYSTEM TABLE"
        echo "============================================================"
        echo

        if [ -r /etc/fstab ]; then

            grep -Ev \
                '^[[:space:]]*(#|$)' \
                /etc/fstab

        else

            echo "Unable to read /etc/fstab."

        fi


        ##################################################
        # 17. Overall Summary
        ##################################################

        echo
        echo "============================================================"
        echo " 17. SYSTEM SUMMARY"
        echo "============================================================"
        echo

        echo "Hostname         : $(hostname)"
        echo "Normal Users     : ${total_users:-0}"
        echo "Groups           : ${total_groups:-0}"
        echo "Running Services : ${running_services:-Unknown}"
        echo "Failed Services  : ${failed_services:-Unknown}"

        if command -v getenforce &>/dev/null; then
            echo "SELinux          : $(getenforce)"
        else
            echo "SELinux          : Unknown"
        fi

        if command -v firewall-cmd &>/dev/null &&
           systemctl is-active --quiet firewalld 2>/dev/null; then

            echo "Firewall         : Active"

        else

            echo "Firewall         : Inactive / Unavailable"

        fi

        if [ -n "$failed_login_data" ]; then
            echo "Failed Logins    : Detected"
        else
            echo "Failed Logins    : None Detected"
        fi


        ##################################################
        # Footer
        ##################################################

        echo
        echo "============================================================"
        echo "            End of LinuxFlow Full Report"
        echo "============================================================"

    } > "$report_file" 2>&1


    ##################################################
    # Verify Report
    ##################################################

    if [ ! -f "$report_file" ]; then

        error "Full system report could not be created."
        pause
        return

    fi

    if [ ! -s "$report_file" ]; then

        error "Generated report is empty."
        rm -f "$report_file"
        pause
        return

    fi


    ##################################################
    # Report Information
    ##################################################

    report_size=$(du -h "$report_file" |
        awk '{print $1}')

    report_lines=$(wc -l < "$report_file")

    echo
    success "Full system report generated successfully."

    echo
    echo "Report Name  : $report_name"
    echo "Report Path  : $report_file"
    echo "Report Size  : $report_size"
    echo "Report Lines : $report_lines"

    pause
}



##################################################
# Function : view_reports
# Purpose  : List and view generated reports
##################################################

view_reports() {

    header

    echo "========== View Generated Reports =========="
    echo

    if ! initialize_report_directory; then
        pause
        return
    fi


    ##################################################
    # Load Available Reports
    ##################################################

    reports=()

    while IFS= read -r file
    do
        reports+=("$file")
    done < <(
        find "$REPORT_DIR" \
            -maxdepth 1 \
            -type f \
            -name "linuxflow_*.txt" \
            -printf "%T@ %p\n" 2>/dev/null |
        sort -nr |
        cut -d' ' -f2-
    )


    ##################################################
    # Check Reports
    ##################################################

    if [ "${#reports[@]}" -eq 0 ]; then

        warning "No generated reports found."
        pause
        return

    fi


    ##################################################
    # Display Report List
    ##################################################

    echo "Available Reports:"
    echo

    printf "%-5s %-45s %-10s %-20s\n" \
        "NO." \
        "REPORT NAME" \
        "SIZE" \
        "CREATED"

    printf "%-5s %-45s %-10s %-20s\n" \
        "-----" \
        "---------------------------------------------" \
        "----------" \
        "--------------------"

    index=1

    for file in "${reports[@]}"
    do

        filename=$(basename "$file")

        size=$(du -h "$file" 2>/dev/null |
            awk '{print $1}')

        created=$(date -r "$file" \
            "+%d-%m-%Y %H:%M:%S" 2>/dev/null)

        printf "%-5s %-45s %-10s %-20s\n" \
            "$index" \
            "$filename" \
            "${size:-Unknown}" \
            "${created:-Unknown}"

        ((index++))

    done

    echo
    echo "Total Reports : ${#reports[@]}"
    echo


    ##################################################
    # Select Report
    ##################################################

    read -p "Enter report number to view (0 to cancel): " choice

    if [ "$choice" = "0" ]; then

        warning "Operation cancelled."
        pause
        return

    fi


    ##################################################
    # Validate Selection
    ##################################################

    if [[ ! "$choice" =~ ^[0-9]+$ ]]; then

        error "Invalid report number."
        pause
        return

    fi

    if [ "$choice" -lt 1 ] ||
       [ "$choice" -gt "${#reports[@]}" ]; then

        error "Report number is out of range."
        pause
        return

    fi


    ##################################################
    # Get Selected Report
    ##################################################

    selected_report="${reports[$((choice - 1))]}"

    if [ ! -f "$selected_report" ]; then

        error "Selected report no longer exists."
        pause
        return

    fi

    if [ ! -r "$selected_report" ]; then

        error "Selected report cannot be read."
        pause
        return

    fi


    ##################################################
    # Display Selected Report
    ##################################################

    header

    echo "========== Report Viewer =========="
    echo
    echo "Report : $(basename "$selected_report")"
    echo
    echo "----------------------------------------------"
    echo

    if command -v less &>/dev/null; then

        less "$selected_report"

    elif command -v more &>/dev/null; then

        more "$selected_report"

    else

        cat "$selected_report"

    fi

    pause
}



##################################################
# Function : delete_report
# Purpose  : Delete a generated LinuxFlow report
##################################################

delete_report() {

    header

    echo "========== Delete Report =========="
    echo

    if ! initialize_report_directory; then
        pause
        return
    fi


    ##################################################
    # Load Available Reports
    ##################################################

    reports=()

    while IFS= read -r file
    do
        reports+=("$file")
    done < <(
        find "$REPORT_DIR" \
            -maxdepth 1 \
            -type f \
            -name "linuxflow_*.txt" \
            -printf "%T@ %p\n" 2>/dev/null |
        sort -nr |
        cut -d' ' -f2-
    )


    ##################################################
    # Check Reports
    ##################################################

    if [ "${#reports[@]}" -eq 0 ]; then

        warning "No generated reports found."
        pause
        return

    fi


    ##################################################
    # Display Reports
    ##################################################

    echo "Available Reports:"
    echo

    printf "%-5s %-45s %-10s %-20s\n" \
        "NO." \
        "REPORT NAME" \
        "SIZE" \
        "CREATED"

    printf "%-5s %-45s %-10s %-20s\n" \
        "-----" \
        "---------------------------------------------" \
        "----------" \
        "--------------------"

    index=1

    for file in "${reports[@]}"
    do

        filename=$(basename "$file")

        size=$(du -h "$file" 2>/dev/null |
            awk '{print $1}')

        created=$(date -r "$file" \
            "+%d-%m-%Y %H:%M:%S" 2>/dev/null)

        printf "%-5s %-45s %-10s %-20s\n" \
            "$index" \
            "$filename" \
            "${size:-Unknown}" \
            "${created:-Unknown}"

        ((index++))

    done

    echo
    echo "Total Reports : ${#reports[@]}"
    echo


    ##################################################
    # Select Report
    ##################################################

    read -p "Enter report number to delete (0 to cancel): " choice

    if [ "$choice" = "0" ]; then

        warning "Operation cancelled."
        pause
        return

    fi


    ##################################################
    # Validate Selection
    ##################################################

    if [[ ! "$choice" =~ ^[0-9]+$ ]]; then

        error "Invalid report number."
        pause
        return

    fi

    if [ "$choice" -lt 1 ] ||
       [ "$choice" -gt "${#reports[@]}" ]; then

        error "Report number is out of range."
        pause
        return

    fi


    ##################################################
    # Selected Report
    ##################################################

    selected_report="${reports[$((choice - 1))]}"
    selected_name=$(basename "$selected_report")

    if [ ! -f "$selected_report" ]; then

        error "Selected report no longer exists."
        pause
        return

    fi


    ##################################################
    # Display Report Information
    ##################################################

    echo
    echo "Selected Report:"
    echo "----------------------------------------------"

    echo "Name    : $selected_name"
    echo "Size    : $(du -h "$selected_report" 2>/dev/null | awk '{print $1}')"
    echo "Created : $(date -r "$selected_report" '+%d-%m-%Y %H:%M:%S' 2>/dev/null)"

    echo
    warning "Deleted reports cannot be recovered."
    echo


    ##################################################
    # Confirmation
    ##################################################

    read -p "Delete '$selected_name'? (Y/N): " confirm

    case "$confirm" in

        Y|y)

            if rm -- "$selected_report"; then

                success "Report deleted successfully."

                echo
                echo "Deleted Report : $selected_name"

            else

                error "Failed to delete report."

            fi
            ;;

        N|n)

            warning "Operation cancelled."
            ;;

        *)

            error "Invalid choice."
            ;;

    esac

    pause
}


##################################################
# Function : report_menu
# Purpose  : Display Report Generator Menu
##################################################

report_menu() {

    while true
    do

        header

        echo "========== Report Generator =========="
        echo
        echo "1. Generate System Summary Report"
        echo "2. Generate User & Group Report"
        echo "3. Generate Storage Report"
        echo "4. Generate Service Report"
        echo "5. Generate Security Report"
        echo "6. Generate Full System Report"
        echo "7. View Generated Reports"
        echo "8. Delete Report"
        echo
        echo "0. Back"
        echo

        read -p "Choose Option : " choice

        case "$choice" in

            1)
                generate_system_report
                ;;

            2)
                generate_user_group_report
                ;;
            
            3) 
                generate_storage_report
                ;;

            4)
                generate_service_report
                ;;

            5)
                generate_security_report
                ;;

            6)
                generate_full_report
                ;;

            7)
                view_reports
                ;;

            8)
                delete_report
                ;;

            0)
                break
                ;;

            *)
                error "Invalid Option"
                pause
                ;;

        esac

    done
}