
############################################
# LinuxFlow Configuration
############################################

APP_NAME="LinuxFlow"

VERSION="0.1.0"

AUTHOR="Kanchan Prajapat"

LOG_DIR="$SCRIPT_DIR/logs"

BACKUP_DIR="$SCRIPT_DIR/backups"

REPORT_DIR="$SCRIPT_DIR/reports"

LOG_FILE="$LOG_DIR/activity.log"

DATE_FORMAT="%d-%m-%Y %H:%M:%S"

DEFAULT_EDITOR="vi"

ENABLE_LOGGING=true

THEME=dark