############################################
# LinuxFlow Configuration
############################################

############################################
# LinuxFlow Configuration
############################################

APP_NAME="LinuxFlow"

VERSION="0.1.0"

AUTHOR="Kanchan Prajapat"

LOG_FILE="./logs/activity.log"

BACKUP_DIR="./backups"

REPORT_DIR="./reports"

DATE_FORMAT="%d-%m-%Y %H:%M:%S"

DEFAULT_EDITOR="vi"

ENABLE_LOGGING=true

THEME=dark